services:
  - type: web
    name: weather-dashboard
    env: node
    plan: free
    buildCommand: |
      cd client && npm ci && npm run build
      cd ../server && npm ci
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
